# Generated by Django 2.0.7 on 2018-08-17 20:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Found',
            fields=[
                ('instance_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('instance_time', models.DateTimeField(auto_now_add=True)),
                ('item_name', models.CharField(max_length=255)),
                ('item_category', models.CharField(choices=[('El', 'Electronics'), ('Bo', 'Books'), ('Ba', 'Bags'), ('Cy', 'Cycles'), ('At', 'ATM cards'), ('Id', 'ID cards/Medical Booklets'), ('Ke', 'Keys'), ('Ca', 'Cash'), ('Um', 'Umbrellas'), ('Wa', 'Wallets'), ('Jw', 'Jewellery'), ('Ad', 'Adhaar Cards'), ('Ot', 'Others')], max_length=255)),
                ('place', models.CharField(max_length=255)),
                ('date', models.DateField(default=datetime.date.today)),
                ('item_desc', models.TextField(blank=True)),
                ('item_status', models.CharField(max_length=255)),
                ('reported_spam', models.BooleanField(default=False)),
                ('item_is_spam', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Found',
                'verbose_name_plural': 'Report Found',
            },
        ),
        migrations.CreateModel(
            name='Lost',
            fields=[
                ('instance_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('instance_time', models.DateTimeField(auto_now_add=True)),
                ('item_name', models.CharField(max_length=255)),
                ('item_category', models.CharField(choices=[('El', 'Electronics'), ('Bo', 'Books'), ('Ba', 'Bags'), ('Cy', 'Cycles'), ('At', 'ATM cards'), ('Id', 'ID cards/Medical Booklets'), ('Ke', 'Keys'), ('Ca', 'Cash'), ('Um', 'Umbrellas'), ('Wa', 'Wallets'), ('Jw', 'Jewellery'), ('Ad', 'Adhaar Cards'), ('Ot', 'Others')], max_length=255)),
                ('place', models.CharField(max_length=255)),
                ('date', models.DateField(default=datetime.date.today)),
                ('item_desc', models.TextField(blank=True)),
                ('item_status', models.CharField(max_length=255)),
                ('reported_spam', models.BooleanField(default=False)),
                ('item_is_spam', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Lost',
                'verbose_name_plural': 'Report Lost',
            },
        ),
    ]
