# Generated by Django 2.0.7 on 2018-08-17 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LostFound', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='found',
            name='email',
        ),
        migrations.RemoveField(
            model_name='found',
            name='ph_no',
        ),
        migrations.RemoveField(
            model_name='found',
            name='residence',
        ),
        migrations.RemoveField(
            model_name='lost',
            name='email',
        ),
        migrations.RemoveField(
            model_name='lost',
            name='ph_no',
        ),
        migrations.RemoveField(
            model_name='lost',
            name='residence',
        ),
    ]
