# Generated by Django 2.0.7 on 2018-08-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LostFound', '0002_auto_20180817_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='found',
            name='reported_spam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lost',
            name='reported_spam',
            field=models.BooleanField(default=False),
        ),
    ]
